2023-07-30 20:35:51,259.continuous_location.INFO =============================================================
2023-07-30 20:35:51,267.continuous_location.INFO Today is 2023-07-30 at 08:35 PM
2023-07-30 20:35:51,292.continuous_location.INFO This file is running on: nt Windows 10
2023-07-30 20:35:51,292.continuous_location.INFO The Python version is: 3.11.4
2023-07-30 20:35:51,292.continuous_location.INFO The active environment path is:   C:\Users\ctrog\OneDrive\Documents\Data Analytics Masters\GIT Hub\cintel-05-live-updates\.venv
2023-07-30 20:35:51,292.continuous_location.INFO The current working directory is: C:\Users\ctrog\OneDrive\Documents\Data Analytics Masters\GIT Hub\cintel-05-live-updates
2023-07-30 20:35:51,292.continuous_location.INFO =============================================================
2023-07-30 20:36:22,556.continuous_location.INFO Calling update_csv_location
2023-07-30 20:36:22,556.continuous_location.INFO update_interval: 60
2023-07-30 20:36:22,556.continuous_location.INFO total_runtime: 900
2023-07-30 20:36:22,556.continuous_location.INFO num_updates: 10
2023-07-30 20:36:22,556.continuous_location.INFO Initialized csv file at C:\Users\ctrog\OneDrive\Documents\Data Analytics Masters\GIT Hub\cintel-05-live-updates\data\mtcars_location.csv
2023-07-30 20:36:22,564.continuous_location.INFO Calling get_temperature_from_openweathermap for {lat}, {long}}
2023-07-30 20:36:22,564.continuous_location.INFO Calling fetch_from_url for https://api.openweathermap.org/data/2.5/weather?lat=47.903237&lon=-91.867087&appid=81579cec5f063b66d5479b9bd4a80b6d&units=imperial
2023-07-30 20:36:22,902.continuous_location.ERROR ERROR in update_csv_location: name 'temp_F' is not defined
